# Generated by Django 4.2.3 on 2023-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_remove_profile_service_profile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="linkxdate",
            field=models.FileField(upload_to="linkxdate"),
        ),
    ]
