# Generated by Django 4.2.3 on 2023-07-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_profile_linkxdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="docs",
            field=models.FileField(default="exit", upload_to="docs"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkxdate",
            field=models.FileField(blank=True, upload_to="linkxdate"),
        ),
    ]
