# Generated by Django 4.2.3 on 2023-07-15 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to="product/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Includes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("tags", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "quantity_choose",
                    models.CharField(
                        choices=[("bulk", "bulk"), ("item", "item"), ("", "")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "new"), ("used", "used"), ("", "")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("weight", models.PositiveIntegerField(default=0)),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[
                            ("kg", "kilograms"),
                            ("lbs", "pounds"),
                            ("gm", "grams"),
                        ],
                        default="kg",
                        max_length=5,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        max_length=30, validators=[product.models.validate_dimensions]
                    ),
                ),
                ("is_digital", models.BooleanField(default=False)),
                ("is_pickup", models.BooleanField(default=False)),
                (
                    "expedite_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("size", models.CharField(max_length=200)),
                (
                    "delivery_time_1_2_day",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "delivery_time_2_3_day",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "delivery_time_3_5_day",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "delivery_time_1_week",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.ManyToManyField(related_name="colors", to="product.color"),
                ),
                (
                    "include",
                    models.ManyToManyField(
                        related_name="includes", to="product.includes"
                    ),
                ),
                (
                    "product_images",
                    models.ManyToManyField(blank=True, to="product.images"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
